plugins:
  yearly_review_enabled:
    default: false
    client: true
  yearly_review_categories:
    type: category_list
    default: ""
  yearly_review_exclude_staff:
    default: true
  yearly_review_include_user_stats:
    default: true
  yearly_review_publish_category:
    type: category
    default: ""
  yearly_review_featured_badge:
    default: ""
