plugins:
  yearly_review_enabled:
    default: true
    client: true
  yearly_review_title:
    default: "2018 in Review"
  yearly_review_categories:
    type: category_list
    default: ''
  yearly_review_publish_category:
    type: category
    default: ''
  yearly_review_featured_badge:
    default: ''
